---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: javawebapp
  name: java-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      containers:
        - image: 102402/javaapp
          name: javawebapp
          ports:
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: java-service
spec:
  type: NodePort
  ports: 
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapp 
